# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0006_auto_20170720_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_id', models.TextField()),
                ('payload', models.BinaryField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('remote', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activitypub.Person')),
            ],
        ),
    ]
