# Generated by Django 3.2.3 on 2021-05-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0008_auto_20170802_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activitypub.person'),
        ),
        migrations.AlterField(
            model_name='note',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='activitypub.person'),
        ),
    ]
